version: '3.1'
services:
  db:
    build: "./postgres"
    restart: always
    environment:
      - POSTGRES_USER=stockx
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=stockx
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node:
    build: "./node"
    command: npm run start
    environment:
      - NODE_ENV=production
      - PORT=3000
      - PGHOST=db
      - PGUSER=stockx
      - PGDATABASE=stockx
      - PGPASSWORD=challenge
      - PGPORT=5432
    depends_on:
      - db
    ports:
      - '3000:3000'
    expose:
      - "3000"
