version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=stockx
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_DB=stockx
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  node:
    image: "node:8"
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - PORT=7000
    working_dir: /root/node
    volumes:
      - ./node:/root/node:cached
    ports:
      - '7000:7000'
    expose:
      - "7000"
