insert into ShoeRatings (ShoeID, Rating) 
    values (1, 1), 
        (1, 2), 
        (1, 2), 
        (1, 3), 
        (1, 2), 
        (1, 3), 
        (1, 2), 
        (1, 2), 
        (1, 3), 
        (1, 4), 
        (1, 2), 
        (1, 5), 
        (1, 2), 
        (1, 3);